[package]
name = "messages-api"
version = "0.1.10"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.5"
serde_valid = "0.25.0"
payment-message = "0.1.7"
utoipa = { version = "4.0", features = ["actix_extras"] }
