[package]
name = "validator-service"
version = "0.1.1"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.5"  # For XML parsing
payment-message = "0.1.2"
serde_valid = "0.25.0"
