name: Build, Publish Docker Image, and Tag Version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-release
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-release
          version: '^0.25'

      - name: Configure git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Run tests
        run: cargo test

      - name: Release and publish crates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cargo release patch --execute --no-confirm --no-publish

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with version tag and latest tag
        run: |
          docker build -t harishankarn/payment-messages-api:${{ env.NEW_VERSION }} .
          docker tag harishankarn/payment-messages-api:${{ env.NEW_VERSION }} harishankarn/payment-messages-api:latest

      - name: Push both versioned and latest Docker image tags to Docker Hub
        run: |
          docker push harishankarn/payment-messages-api:${{ env.NEW_VERSION }}
          docker push harishankarn/payment-messages-api:latest
