name: Auth GCP TEST

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Authenticate with GCP using google-github-actions/auth
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Setup Google Cloud SDK without passing service_account_key
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        version: 'latest'

    # Authenticate Docker with Google Container Registry via gcloud
    - name: Authenticate Docker to GCR
      run: |
        gcloud auth configure-docker gcr.io
