name: Build, Publish Docker Image, and Tag Version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Run tests
      run: cargo test

    - name: Extract version from Cargo.toml
      id: version
      run: |
        VERSION=$(grep '^version =' Cargo.toml | head -n 1 | cut -d '"' -f 2)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image with Cargo version
      run: docker build -t harishankarn/open-payments-validator-service:${{ env.VERSION }} .

    - name: Push Docker image to Docker Hub
      run: docker push harishankarn/open-payments-validator-service:${{ env.VERSION }}

    - name: Configure Git for GitHub Actions
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Tag the repository with the crate version and push
      env:
        GITHUB_PAT: ${{ secrets.GH_PAT }}  # Use your GH_PAT secret here
      run: |
        git tag -a "v${{ env.VERSION }}" -m "Version ${{ env.VERSION }} release"
        git remote set-url origin https://$GITHUB_PAT@github.com/Open-Payments/messages.git
        git push origin "v${{ env.VERSION }}"