name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Run this action when code is pushed to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t harishankarn/open-payments-validator-service:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push harishankarn/open-payments-validator-service:latest
